all: HelloWorldMPI HelloWorldBlockingMPI

HelloWorldMPI: HelloWorldMPI.c
	mpicc -o HelloWorldMPI HelloWorldMPI.c 

HelloWorldBlockingMPI: HelloWorldBlockingMPI.c
	mpicc -o HelloWorldBlockingMPI HelloWorldBlockingMPI.c